const translations = {
    en: {
        "nav-works": "How it works",
        "nav-specs": "Specs",
        "nav-faq": "FAQ",
        "hero-title": "Your keyboard is holding you back.",
        "hero-outcome": "Your thoughts at 150 WPM. Free. Forever.",
        "btn-break": "Break the ceiling.",
        "tt-badge-kb": "40 wpm",
        "tt-badge-fn": "150 wpm",
        "tt-title-kb": "keyboard",
        "tt-title-fn": "fnkey",
        "tt-status": "waiting...",
        "tt-listening": "listening (hold)...",
        "tt-done": "done (150 wpm)",
        "sp-ph": "PH Upvotes",
        "sp-pod": "Product of Day",
        "sp-am": "awesome-mac",
        "sp-gh": "GitHub Cloners",
        "faq-q1": "Do I need my own Deepgram API key?",
        "faq-a1": "Yes, but it takes 30 seconds. Sign up at deepgram.com, grab a free API key, paste it into the app. Deepgram's free tier gives you 45,000 minutes — that's enough for months of heavy use. Groq works as a fallback.",
        "faq-q2": "Is my audio saved anywhere?",
        "faq-a2": "Never. Audio is streamed directly via WebSocket and is not saved to disk. When the macOS yellow mic indicator is off, the app is 100% deaf.",
        "faq-q3": "Does it work with any app?",
        "faq-a3": "Yes. It simulates native keyboard input. If you can type there, you can dictate there (Cursor, Slack, Chrome, etc).",
        "faq-q4": "Why is it free?",
        "faq-a4": "We built it for ourselves because competitors charge $15/mo for batch audio processing. We believe core utilities should be open source. You can't lose. We can't take your money — it doesn't exist. Worst case: brew uninstall fnkey. That's it.",
        "cat-speed": "cat speed.log",
        "p-speed": "Not batch recording. Audio streams directly to Deepgram Nova-3 in real time via WebSocket. By the time you release the Fn key, the transcription is already done. 54% lower word error rate on streaming vs batch competitors.",
        "cat-trust": "cat trust.log",
        "p-trust": "The microphone is dead until you press Fn. The macOS yellow dot is your hardware privacy proof, not a corporate promise. Fully open source (GPL-3.0).",
        "cat-freedom": "cat freedom.log",
        "p-freedom": "Competitors charge $15/month for slower tools. Keep that $180/year in your pocket. Features Groq fallback API so you're never locked into a single provider.",
        "term-install": "bash — install",
        "copy-hint": "click to copy",
        "copy-status": "copied to clipboard",
        "deploy-sub": "or request",
        "footer-obs": "Built with obsession by humans",
        "version": "version",
        "license": "license",
        "engine": "engine",
        "fallback": "fallback",
        "repo": "repo",
        "panic": "Scared? We were just joking, your command is in the clipboard. Good luck!",
        "sp-listed": "Listed",
        "mc-v": "v1.2.0 · macOS 12.0+ · Open Source",
        "boot-1": "[ OK ] Initializing core systems...",
        "boot-2": "[ OK ] Mounting memory banks...",
        "boot-3": "[ OK ] Loading neural engine...",
        "boot-4": "[ OK ] Establishing secure uplink...",
        "boot-5": "[ OK ] Booting FnKey v1.0.0...",

        // Game Canvas Defaults
        "game_kb": "⌨ keyboard",
        "game_fn": "🎙 fnkey",
        "game_l1": "— letter by letter",
        "game_l2": "— backspace, retype",
        "game_l3": "— fingers limit you",
        "game_r1": "— thought by thought",
        "game_r2": "— streams as you speak",
        "game_r3": "— voice sets you free",
        "game_just_hold": "just hold",
        "game_space": "[ space ]",
        "game_or_click": "or click ↓",
        "game_done": "done",
        "site-title": "FnKey — Real-time Dictation"
    }
};

window.currentLang = 'en';
